"""add_simulations_core_tables
Revision ID: 383c5f20fdcd
Revises: c05833cd04f9
Create Date: 2026-01-30 23:27:07.366791
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '383c5f20fdcd'
down_revision = 'c05833cd04f9'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('intro_video_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True, comment='beginner, intermediate, advanced'),
    sa.Column('estimated_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('has_certificate', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True, comment='draft, published, archived'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_category_id'), 'simulations', ['category_id'], unique=False)
    op.create_index(op.f('ix_simulations_company_id'), 'simulations', ['company_id'], unique=False)
    op.create_index(op.f('ix_simulations_id'), 'simulations', ['id'], unique=False)
    op.create_index(op.f('ix_simulations_slug'), 'simulations', ['slug'], unique=True)
    op.create_index(op.f('ix_simulations_state'), 'simulations', ['state'], unique=False)
    op.create_table('simulation_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('intro_video_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_modules_id'), 'simulation_modules', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_modules_simulation_id'), 'simulation_modules', ['simulation_id'], unique=False)
    op.create_table('module_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('instructor_name', sa.String(length=150), nullable=True),
    sa.Column('instructor_role', sa.String(length=150), nullable=True),
    sa.Column('instructor_video_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['simulation_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_tasks_id'), 'module_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_module_tasks_module_id'), 'module_tasks', ['module_id'], unique=False)
    op.create_table('model_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_explanation_url', sa.String(length=500), nullable=True),
    sa.Column('resource_url', sa.String(length=500), nullable=True),
    sa.Column('key_learnings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['module_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_model_answers_id'), 'model_answers', ['id'], unique=False)
    op.create_table('task_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='pdf, excel, link'),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['module_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_resources_id'), 'task_resources', ['id'], unique=False)
    op.create_index(op.f('ix_task_resources_task_id'), 'task_resources', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_resources_task_id'), table_name='task_resources')
    op.drop_index(op.f('ix_task_resources_id'), table_name='task_resources')
    op.drop_table('task_resources')
    op.drop_index(op.f('ix_model_answers_id'), table_name='model_answers')
    op.drop_table('model_answers')
    op.drop_index(op.f('ix_module_tasks_module_id'), table_name='module_tasks')
    op.drop_index(op.f('ix_module_tasks_id'), table_name='module_tasks')
    op.drop_table('module_tasks')
    op.drop_index(op.f('ix_simulation_modules_simulation_id'), table_name='simulation_modules')
    op.drop_index(op.f('ix_simulation_modules_id'), table_name='simulation_modules')
    op.drop_table('simulation_modules')
    op.drop_index(op.f('ix_simulations_state'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_slug'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_company_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_category_id'), table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
