"""baseline
Revision ID: 418c1b16ee37
Revises: 77fa938e6a6d
Create Date: 2026-01-11 23:16:14.883011
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '418c1b16ee37'
down_revision = '77fa938e6a6d'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
