"""fase6_motor_progreso_y_skills
Revision ID: 421658025665
Revises: cffe39e02ec2
Create Date: 2026-03-04 20:35:57.361074
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '421658025665'
down_revision = 'cffe39e02ec2'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
