"""add_skills_and_progress
Revision ID: 6df5fed3d32b
Revises: a88ccd6834a7
Create Date: 2026-02-23 18:45:08.338368
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6df5fed3d32b'
down_revision = 'a88ccd6834a7'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_skill_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False, comment='technical, soft, language, tool'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalog_skill_id'], ['skills_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_catalog_skill_id'), 'skills', ['catalog_skill_id'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('user_simulation_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='progressstatus'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='0-100 score'),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_time_minutes', sa.Integer(), nullable=True),
    sa.Column('current_module_id', sa.Integer(), nullable=True),
    sa.Column('current_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_module_id'], ['simulation_modules.id'], ),
    sa.ForeignKeyConstraint(['current_task_id'], ['module_tasks.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_simulation_progress_id'), 'user_simulation_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_simulation_progress_simulation_id'), 'user_simulation_progress', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_user_simulation_progress_status'), 'user_simulation_progress', ['status'], unique=False)
    op.create_index(op.f('ix_user_simulation_progress_user_id'), 'user_simulation_progress', ['user_id'], unique=False)
    op.create_table('usuarios_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_usuarios_empresa_empresa_id'), 'usuarios_empresa', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios_empresa', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_empresa_user_id'), 'usuarios_empresa', ['user_id'], unique=False)
    op.drop_index(op.f('ix_company_users_company_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_email'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_invitation_token'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_role'), table_name='company_users')
    op.drop_table('company_users')
    op.add_column('careers', sa.Column('nombre', sa.String(length=200), nullable=False))
    op.add_column('careers', sa.Column('codigo', sa.String(length=50), nullable=True))
    op.alter_column('careers', 'university_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('careers_code_key'), 'careers', type_='unique')
    op.drop_column('careers', 'description')
    op.drop_column('careers', 'name')
    op.drop_column('careers', 'is_active')
    op.drop_column('careers', 'duration_semesters')
    op.drop_column('careers', 'modality')
    op.drop_column('careers', 'code')
    op.add_column('empresas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('empresas', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('empresas', 'nombre_empresa',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('empresas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('empresas', 'tipo_empresa',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('empresas', 'pais',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('empresas', 'ciudad',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('empresas', 'descripcion_corta',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('empresas', 'es_partner_activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('empresas', 'esta_activo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('empresas', 'calificacion_promedio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('empresas', 'url_banner')
    op.drop_column('empresas', 'linkedin_url')
    op.drop_column('empresas', 'twitter_url')
    op.drop_column('empresas', 'creado_en')
    op.drop_column('empresas', 'max_simulaciones_activas')
    op.drop_column('empresas', 'mision')
    op.drop_column('empresas', 'url_logo')
    op.drop_column('empresas', 'email_contacto')
    op.drop_column('empresas', 'max_usuarios_admin')
    op.drop_column('empresas', 'url_sitio_web')
    op.drop_column('empresas', 'telefono')
    op.drop_column('empresas', 'vision')
    op.drop_column('empresas', 'actualizado_en')
    op.drop_column('empresas', 'total_usuarios_inscritos')
    op.drop_column('empresas', 'color_primario')
    op.drop_column('empresas', 'descripcion_completa')
    op.drop_column('empresas', 'total_simulaciones')
    op.drop_column('empresas', 'industria_secundaria')
    op.add_column('simulations', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('simulations', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('simulations', sa.Column('total_spots', sa.Integer(), nullable=True, comment='0 means unlimited'))
    op.add_column('simulations', sa.Column('available_spots', sa.Integer(), nullable=True))
    op.alter_column('task_resources', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pdf, excel, link',
               existing_nullable=True)
    op.add_column('universities', sa.Column('nombre', sa.String(length=200), nullable=False))
    op.add_column('universities', sa.Column('slug', sa.String(length=200), nullable=False))
    op.add_column('universities', sa.Column('dominio', sa.String(length=100), nullable=True))
    op.add_column('universities', sa.Column('tipo', sa.String(length=50), nullable=True))
    op.add_column('universities', sa.Column('pais', sa.String(length=100), nullable=True))
    op.add_column('universities', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('universities', sa.Column('direccion', sa.String(length=300), nullable=True))
    op.add_column('universities', sa.Column('es_partner', sa.Boolean(), nullable=True))
    op.add_column('universities', sa.Column('esta_activo', sa.Boolean(), nullable=True))
    op.add_column('universities', sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('universities', sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_universities_code'), table_name='universities')
    op.create_index(op.f('ix_universities_nombre'), 'universities', ['nombre'], unique=True)
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.drop_constraint(op.f('universities_city_id_fkey'), 'universities', type_='foreignkey')
    op.drop_column('universities', 'description')
    op.drop_column('universities', 'website')
    op.drop_column('universities', 'name')
    op.drop_column('universities', 'is_active')
    op.drop_column('universities', 'university_type')
    op.drop_column('universities', 'accreditation')
    op.drop_column('universities', 'address')
    op.drop_column('universities', 'code')
    op.drop_column('universities', 'logo_url')
    op.drop_column('universities', 'email')
    op.drop_column('universities', 'acronym')
    op.drop_column('universities', 'phone')
    op.drop_column('universities', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('acronym', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('logo_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('universities', sa.Column('address', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('accreditation', postgresql.ENUM('A', 'B', 'C', 'pending', name='accreditationtype'), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('university_type', postgresql.ENUM('public', 'private', 'cofinanced', name='universitytype'), autoincrement=False, nullable=False))
    op.add_column('universities', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('universities', sa.Column('website', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('universities', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('universities_city_id_fkey'), 'universities', 'cities', ['city_id'], ['id'])
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.drop_index(op.f('ix_universities_nombre'), table_name='universities')
    op.create_index(op.f('ix_universities_code'), 'universities', ['code'], unique=True)
    op.drop_column('universities', 'actualizado_en')
    op.drop_column('universities', 'creado_en')
    op.drop_column('universities', 'esta_activo')
    op.drop_column('universities', 'es_partner')
    op.drop_column('universities', 'direccion')
    op.drop_column('universities', 'ciudad')
    op.drop_column('universities', 'pais')
    op.drop_column('universities', 'tipo')
    op.drop_column('universities', 'dominio')
    op.drop_column('universities', 'slug')
    op.drop_column('universities', 'nombre')
    op.alter_column('task_resources', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               comment='pdf, excel, link',
               existing_nullable=True)
    op.drop_column('simulations', 'available_spots')
    op.drop_column('simulations', 'total_spots')
    op.drop_column('simulations', 'end_date')
    op.drop_column('simulations', 'start_date')
    op.add_column('empresas', sa.Column('industria_secundaria', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('total_simulaciones', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('descripcion_completa', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('color_primario', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('total_usuarios_inscritos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('actualizado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('vision', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('telefono', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('url_sitio_web', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('max_usuarios_admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('email_contacto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('url_logo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('mision', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('max_simulaciones_activas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('twitter_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('url_banner', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.alter_column('empresas', 'calificacion_promedio',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('empresas', 'esta_activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('empresas', 'es_partner_activo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('empresas', 'descripcion_corta',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('empresas', 'ciudad',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('empresas', 'pais',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('empresas', 'tipo_empresa',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('empresas', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('empresas', 'nombre_empresa',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('empresas', 'updated_at')
    op.drop_column('empresas', 'created_at')
    op.add_column('careers', sa.Column('code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('careers', sa.Column('modality', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('careers', sa.Column('duration_semesters', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('careers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('careers', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('careers', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('careers_code_key'), 'careers', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('careers', 'university_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('careers', 'codigo')
    op.drop_column('careers', 'nombre')
    op.create_table('company_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Recruiter, Content Manager, HR Director'),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='owner, admin, editor, viewer'),
    sa.Column('can_create_simulations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_edit_simulations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_publish_simulations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_archive_simulations', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_view_candidates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_contact_candidates', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_export_data', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_manage_users', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('can_view_billing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_access', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_accesses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invited_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invitation_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('invitation_accepted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['empresas.id'], name=op.f('company_users_company_id_fkey')),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['company_users.id'], name=op.f('company_users_invited_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_users_pkey'))
    )
    op.create_index(op.f('ix_company_users_role'), 'company_users', ['role'], unique=False)
    op.create_index(op.f('ix_company_users_invitation_token'), 'company_users', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_company_users_id'), 'company_users', ['id'], unique=False)
    op.create_index(op.f('ix_company_users_email'), 'company_users', ['email'], unique=True)
    op.create_index(op.f('ix_company_users_company_id'), 'company_users', ['company_id'], unique=False)
    op.drop_index(op.f('ix_usuarios_empresa_user_id'), table_name='usuarios_empresa')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios_empresa')
    op.drop_index(op.f('ix_usuarios_empresa_empresa_id'), table_name='usuarios_empresa')
    op.drop_table('usuarios_empresa')
    op.drop_index(op.f('ix_user_simulation_progress_user_id'), table_name='user_simulation_progress')
    op.drop_index(op.f('ix_user_simulation_progress_status'), table_name='user_simulation_progress')
    op.drop_index(op.f('ix_user_simulation_progress_simulation_id'), table_name='user_simulation_progress')
    op.drop_index(op.f('ix_user_simulation_progress_id'), table_name='user_simulation_progress')
    op.drop_table('user_simulation_progress')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_catalog_skill_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
