"""fase12_infrastructure
Revision ID: 72c9aac5e073
Revises: c5ef71b33e6b
Create Date: 2026-03-10 18:28:46.728508
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '72c9aac5e073'
down_revision = 'c5ef71b33e6b'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp_requerida', sa.Integer(), nullable=False),
    sa.Column('nombre_nivel', sa.String(length=100), nullable=True, comment='Novato, Aprendiz, Experto, Maestro'),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('recompensa_xp_bonus', sa.Integer(), nullable=False),
    sa.Column('recompensas_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='Items especiales desbloqueados al alcanzar este nivel'),
    sa.Column('recompensas_desbloqueos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='Features de plataforma que se desbloquean'),
    sa.Column('icono', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('badge_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_niveles_id'), 'niveles', ['id'], unique=False)
    op.create_index(op.f('ix_niveles_nivel'), 'niveles', ['nivel'], unique=True)
    op.create_index(op.f('ix_niveles_xp_requerida'), 'niveles', ['xp_requerida'], unique=False)
    op.create_table('habilidades_simulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('habilidad_id', sa.Integer(), nullable=False),
    sa.Column('xp_ganado', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=3, scale=2), nullable=False, comment='Importancia relativa 0.0-2.0'),
    sa.Column('es_habilidad_principal', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['habilidad_id'], ['skills_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulacion_id', 'habilidad_id', name='uq_simulacion_habilidad')
    )
    op.create_index(op.f('ix_habilidades_simulacion_habilidad_id'), 'habilidades_simulacion', ['habilidad_id'], unique=False)
    op.create_index(op.f('ix_habilidades_simulacion_id'), 'habilidades_simulacion', ['id'], unique=False)
    op.create_index(op.f('ix_habilidades_simulacion_simulacion_id'), 'habilidades_simulacion', ['simulacion_id'], unique=False)
    op.create_table('mentores_simulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('rol_en_simulacion', sa.String(length=50), nullable=False, comment='mentor_principal, supervisor, colega, experto_invitado'),
    sa.Column('descripcion_rol', sa.Text(), nullable=True),
    sa.Column('disponible_chat_global', sa.Boolean(), nullable=False),
    sa.Column('orden_presentacion', sa.Integer(), nullable=False),
    sa.Column('mensaje_bienvenida', sa.Text(), nullable=True),
    sa.Column('aparece_en_modulos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='IDs de módulos donde aparece este mentor'),
    sa.Column('aparece_en_tareas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='IDs de tareas donde aparece este mentor'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentores_virtuales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('simulacion_id', 'mentor_id', name='uq_simulacion_mentor')
    )
    op.create_index(op.f('ix_mentores_simulacion_id'), 'mentores_simulacion', ['id'], unique=False)
    op.create_index(op.f('ix_mentores_simulacion_mentor_id'), 'mentores_simulacion', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentores_simulacion_simulacion_id'), 'mentores_simulacion', ['simulacion_id'], unique=False)
    op.create_table('autenticaciones_sociales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('proveedor', sa.String(length=50), nullable=False, comment='google, linkedin, github, microsoft, apple'),
    sa.Column('proveedor_usuario_id', sa.String(length=255), nullable=False, comment='ID único del proveedor'),
    sa.Column('email_proveedor', sa.String(length=255), nullable=True),
    sa.Column('nombre_proveedor', sa.String(length=200), nullable=True),
    sa.Column('avatar_url_proveedor', sa.String(length=500), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expira_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment="['email', 'profile']"),
    sa.Column('metadata_proveedor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=False),
    sa.Column('es_metodo_principal', sa.Boolean(), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_usos', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor', 'proveedor_usuario_id', name='uq_proveedor_usuario_id')
    )
    op.create_index(op.f('ix_autenticaciones_sociales_id'), 'autenticaciones_sociales', ['id'], unique=False)
    op.create_index(op.f('ix_autenticaciones_sociales_usuario_id'), 'autenticaciones_sociales', ['usuario_id'], unique=False)
    op.create_table('logs_autenticacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=False, comment='login_exitoso, login_fallido, logout, token_refresh, password_reset'),
    sa.Column('metodo', sa.String(length=50), nullable=True, comment='email_password, google, linkedin, github'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('plataforma', sa.String(length=50), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('razon_fallo', sa.String(length=200), nullable=True, comment='password_incorrecto, cuenta_bloqueada, 2fa_fallido'),
    sa.Column('codigo_error', sa.String(length=50), nullable=True),
    sa.Column('metadata_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment="Data adicional del evento (NO usar 'metadata' para no chocar con Base.metadata)"),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_autenticacion_creado_en'), 'logs_autenticacion', ['creado_en'], unique=False)
    op.create_index(op.f('ix_logs_autenticacion_id'), 'logs_autenticacion', ['id'], unique=False)
    op.create_index(op.f('ix_logs_autenticacion_tipo_evento'), 'logs_autenticacion', ['tipo_evento'], unique=False)
    op.create_index(op.f('ix_logs_autenticacion_usuario_id'), 'logs_autenticacion', ['usuario_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('tipo_accion', sa.String(length=50), nullable=False, comment='login, api_call, crear_publicacion, enviar_mensaje'),
    sa.Column('contador', sa.Integer(), nullable=False),
    sa.Column('limite_max', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ventana_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ventana_duracion_segundos', sa.Integer(), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limits_bloqueado'), 'rate_limits', ['bloqueado'], unique=False)
    op.create_index(op.f('ix_rate_limits_id'), 'rate_limits', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limits_ip_address'), 'rate_limits', ['ip_address'], unique=False)
    op.create_index(op.f('ix_rate_limits_usuario_id'), 'rate_limits', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_rate_limits_ventana_fin'), 'rate_limits', ['ventana_fin'], unique=False)
    op.create_table('referidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_referidor_id', sa.Integer(), nullable=False),
    sa.Column('usuario_referido_id', sa.Integer(), nullable=False),
    sa.Column('codigo_referido', sa.String(length=20), nullable=False, comment='Código usado para registrarse'),
    sa.Column('recompensa_referidor_xp', sa.Integer(), nullable=False),
    sa.Column('recompensa_referido_xp', sa.Integer(), nullable=False),
    sa.Column('recompensa_adicional', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False, comment='pendiente, completado, expirado'),
    sa.Column('recompensa_reclamada', sa.Boolean(), nullable=False),
    sa.Column('reclamada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requiere_completar_simulacion', sa.Boolean(), nullable=False),
    sa.Column('simulaciones_completadas', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=True, comment='whatsapp, email, redes_sociales'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_referido_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_referidor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_referidor_id', 'usuario_referido_id', name='uq_referidor_referido')
    )
    op.create_index(op.f('ix_referidos_estado'), 'referidos', ['estado'], unique=False)
    op.create_index(op.f('ix_referidos_id'), 'referidos', ['id'], unique=False)
    op.create_index(op.f('ix_referidos_usuario_referido_id'), 'referidos', ['usuario_referido_id'], unique=False)
    op.create_index(op.f('ix_referidos_usuario_referidor_id'), 'referidos', ['usuario_referidor_id'], unique=False)
    op.create_table('sesiones_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_sesion', sa.String(length=500), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('plataforma', sa.String(length=50), nullable=True, comment='web, ios, android, desktop'),
    sa.Column('navegador', sa.String(length=100), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=100), nullable=True),
    sa.Column('dispositivo', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_uso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.Column('revocado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('razon_revocacion', sa.String(length=200), nullable=True, comment='logout, cambio_password, sospechoso'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_usuario_id'), 'sesiones_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_refresh_token'), 'sesiones_usuario', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_sesiones_usuario_revocado'), 'sesiones_usuario', ['revocado'], unique=False)
    op.create_index(op.f('ix_sesiones_usuario_token_sesion'), 'sesiones_usuario', ['token_sesion'], unique=True)
    op.create_index(op.f('ix_sesiones_usuario_usuario_id'), 'sesiones_usuario', ['usuario_id'], unique=False)
    op.create_table('auditoria_empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('admin_dao_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False, comment='crear, editar, verificar, cambiar_plan, desactivar'),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('campos_modificados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_dao_id'], ['admins_dao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_empresas_accion'), 'auditoria_empresas', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_empresas_admin_dao_id'), 'auditoria_empresas', ['admin_dao_id'], unique=False)
    op.create_index(op.f('ix_auditoria_empresas_creado_en'), 'auditoria_empresas', ['creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_empresas_empresa_id'), 'auditoria_empresas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditoria_empresas_id'), 'auditoria_empresas', ['id'], unique=False)
    op.create_table('auditoria_simulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_empresa_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False, comment='crear, editar, publicar, pausar, archivar, eliminar'),
    sa.Column('campos_modificados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True, comment='{ campo: {antes: X, despues: Y} }'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_empresa_id'], ['usuarios_empresa.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_simulaciones_accion'), 'auditoria_simulaciones', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_simulaciones_creado_en'), 'auditoria_simulaciones', ['creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_simulaciones_id'), 'auditoria_simulaciones', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_simulaciones_simulacion_id'), 'auditoria_simulaciones', ['simulacion_id'], unique=False)
    op.create_index(op.f('ix_auditoria_simulaciones_usuario_empresa_id'), 'auditoria_simulaciones', ['usuario_empresa_id'], unique=False)
    op.create_table('auditoria_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('admin_dao_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False, comment='editar_perfil, cambiar_email, resetear_password, bloquear, desbloquear, eliminar'),
    sa.Column('razon', sa.Text(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('campos_modificados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admin_dao_id'], ['admins_dao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_usuarios_accion'), 'auditoria_usuarios', ['accion'], unique=False)
    op.create_index(op.f('ix_auditoria_usuarios_admin_dao_id'), 'auditoria_usuarios', ['admin_dao_id'], unique=False)
    op.create_index(op.f('ix_auditoria_usuarios_creado_en'), 'auditoria_usuarios', ['creado_en'], unique=False)
    op.create_index(op.f('ix_auditoria_usuarios_id'), 'auditoria_usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_auditoria_usuarios_usuario_id'), 'auditoria_usuarios', ['usuario_id'], unique=False)
    op.create_table('configuracion_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('tipo_dato', sa.String(length=50), nullable=False, comment='string, integer, decimal, boolean, json'),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True, comment='gamificacion, notificaciones, integracion, seguridad'),
    sa.Column('es_publico', sa.Boolean(), nullable=False),
    sa.Column('es_modificable', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_por_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por_admin_id'], ['admins_dao.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_sistema_actualizado_por_admin_id'), 'configuracion_sistema', ['actualizado_por_admin_id'], unique=False)
    op.create_index(op.f('ix_configuracion_sistema_categoria'), 'configuracion_sistema', ['categoria'], unique=False)
    op.create_index(op.f('ix_configuracion_sistema_clave'), 'configuracion_sistema', ['clave'], unique=True)
    op.create_index(op.f('ix_configuracion_sistema_id'), 'configuracion_sistema', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_sistema_id'), table_name='configuracion_sistema')
    op.drop_index(op.f('ix_configuracion_sistema_clave'), table_name='configuracion_sistema')
    op.drop_index(op.f('ix_configuracion_sistema_categoria'), table_name='configuracion_sistema')
    op.drop_index(op.f('ix_configuracion_sistema_actualizado_por_admin_id'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    op.drop_index(op.f('ix_auditoria_usuarios_usuario_id'), table_name='auditoria_usuarios')
    op.drop_index(op.f('ix_auditoria_usuarios_id'), table_name='auditoria_usuarios')
    op.drop_index(op.f('ix_auditoria_usuarios_creado_en'), table_name='auditoria_usuarios')
    op.drop_index(op.f('ix_auditoria_usuarios_admin_dao_id'), table_name='auditoria_usuarios')
    op.drop_index(op.f('ix_auditoria_usuarios_accion'), table_name='auditoria_usuarios')
    op.drop_table('auditoria_usuarios')
    op.drop_index(op.f('ix_auditoria_simulaciones_usuario_empresa_id'), table_name='auditoria_simulaciones')
    op.drop_index(op.f('ix_auditoria_simulaciones_simulacion_id'), table_name='auditoria_simulaciones')
    op.drop_index(op.f('ix_auditoria_simulaciones_id'), table_name='auditoria_simulaciones')
    op.drop_index(op.f('ix_auditoria_simulaciones_creado_en'), table_name='auditoria_simulaciones')
    op.drop_index(op.f('ix_auditoria_simulaciones_accion'), table_name='auditoria_simulaciones')
    op.drop_table('auditoria_simulaciones')
    op.drop_index(op.f('ix_auditoria_empresas_id'), table_name='auditoria_empresas')
    op.drop_index(op.f('ix_auditoria_empresas_empresa_id'), table_name='auditoria_empresas')
    op.drop_index(op.f('ix_auditoria_empresas_creado_en'), table_name='auditoria_empresas')
    op.drop_index(op.f('ix_auditoria_empresas_admin_dao_id'), table_name='auditoria_empresas')
    op.drop_index(op.f('ix_auditoria_empresas_accion'), table_name='auditoria_empresas')
    op.drop_table('auditoria_empresas')
    op.drop_index(op.f('ix_sesiones_usuario_usuario_id'), table_name='sesiones_usuario')
    op.drop_index(op.f('ix_sesiones_usuario_token_sesion'), table_name='sesiones_usuario')
    op.drop_index(op.f('ix_sesiones_usuario_revocado'), table_name='sesiones_usuario')
    op.drop_index(op.f('ix_sesiones_usuario_refresh_token'), table_name='sesiones_usuario')
    op.drop_index(op.f('ix_sesiones_usuario_id'), table_name='sesiones_usuario')
    op.drop_table('sesiones_usuario')
    op.drop_index(op.f('ix_referidos_usuario_referidor_id'), table_name='referidos')
    op.drop_index(op.f('ix_referidos_usuario_referido_id'), table_name='referidos')
    op.drop_index(op.f('ix_referidos_id'), table_name='referidos')
    op.drop_index(op.f('ix_referidos_estado'), table_name='referidos')
    op.drop_table('referidos')
    op.drop_index(op.f('ix_rate_limits_ventana_fin'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_usuario_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_ip_address'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_id'), table_name='rate_limits')
    op.drop_index(op.f('ix_rate_limits_bloqueado'), table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_logs_autenticacion_usuario_id'), table_name='logs_autenticacion')
    op.drop_index(op.f('ix_logs_autenticacion_tipo_evento'), table_name='logs_autenticacion')
    op.drop_index(op.f('ix_logs_autenticacion_id'), table_name='logs_autenticacion')
    op.drop_index(op.f('ix_logs_autenticacion_creado_en'), table_name='logs_autenticacion')
    op.drop_table('logs_autenticacion')
    op.drop_index(op.f('ix_autenticaciones_sociales_usuario_id'), table_name='autenticaciones_sociales')
    op.drop_index(op.f('ix_autenticaciones_sociales_id'), table_name='autenticaciones_sociales')
    op.drop_table('autenticaciones_sociales')
    op.drop_index(op.f('ix_mentores_simulacion_simulacion_id'), table_name='mentores_simulacion')
    op.drop_index(op.f('ix_mentores_simulacion_mentor_id'), table_name='mentores_simulacion')
    op.drop_index(op.f('ix_mentores_simulacion_id'), table_name='mentores_simulacion')
    op.drop_table('mentores_simulacion')
    op.drop_index(op.f('ix_habilidades_simulacion_simulacion_id'), table_name='habilidades_simulacion')
    op.drop_index(op.f('ix_habilidades_simulacion_id'), table_name='habilidades_simulacion')
    op.drop_index(op.f('ix_habilidades_simulacion_habilidad_id'), table_name='habilidades_simulacion')
    op.drop_table('habilidades_simulacion')
    op.drop_index(op.f('ix_niveles_xp_requerida'), table_name='niveles')
    op.drop_index(op.f('ix_niveles_nivel'), table_name='niveles')
    op.drop_index(op.f('ix_niveles_id'), table_name='niveles')
    op.drop_table('niveles')
    # ### end Alembic commands ###
