"""fase9_gamificacion_ia
Revision ID: 7c478f85c047
Revises: db3b8b69b41e
Create Date: 2026-03-04 22:53:49.229434
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7c478f85c047'
down_revision = 'db3b8b69b41e'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('icono_url', sa.String(length=500), nullable=True),
    sa.Column('tipo_logro', sa.Enum('BRONCE', 'PLATA', 'ORO', 'PLATINO', name='tipologroenum'), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('recompensa_xp', sa.Integer(), nullable=False),
    sa.Column('recompensa_badge', sa.String(length=100), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_index(op.f('ix_logros_id'), 'logros', ['id'], unique=False)
    op.create_index(op.f('ix_logros_tipo_logro'), 'logros', ['tipo_logro'], unique=False)
    op.create_table('misiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('icono_url', sa.String(length=500), nullable=True),
    sa.Column('objetivo_tipo', sa.String(length=100), nullable=False),
    sa.Column('objetivo_cantidad', sa.Integer(), nullable=False),
    sa.Column('objetivo_metadata', sa.Text(), nullable=True),
    sa.Column('recompensa_xp', sa.Integer(), nullable=False),
    sa.Column('recompensa_items', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('es_diaria', sa.Boolean(), nullable=True),
    sa.Column('es_semanal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misiones_id'), 'misiones', ['id'], unique=False)
    op.create_table('mentores_virtuales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('personalidad', sa.String(length=100), nullable=True),
    sa.Column('prompt_sistema', sa.Text(), nullable=False),
    sa.Column('modelo_ia', sa.String(length=100), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('areas_experiencia', sa.Text(), nullable=True),
    sa.Column('idiomas', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentores_virtuales_empresa_id'), 'mentores_virtuales', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_mentores_virtuales_id'), 'mentores_virtuales', ['id'], unique=False)
    op.create_table('conversaciones_mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'PAUSADA', 'FINALIZADA', name='estadoconversacionenum'), nullable=False),
    sa.Column('total_mensajes', sa.Integer(), nullable=False),
    sa.Column('titulo_conversacion', sa.String(length=300), nullable=True),
    sa.Column('contexto_inicial', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_ultimo_mensaje', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_finalizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentores_virtuales.id'], ),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversaciones_mentor_estado'), 'conversaciones_mentor', ['estado'], unique=False)
    op.create_index(op.f('ix_conversaciones_mentor_id'), 'conversaciones_mentor', ['id'], unique=False)
    op.create_index(op.f('ix_conversaciones_mentor_mentor_id'), 'conversaciones_mentor', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_mentor_simulation_id'), 'conversaciones_mentor', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_mentor_user_id'), 'conversaciones_mentor', ['user_id'], unique=False)
    op.create_table('habilidades_tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('xp_ganado', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills_catalog.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['module_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habilidades_tarea_id'), 'habilidades_tarea', ['id'], unique=False)
    op.create_index(op.f('ix_habilidades_tarea_skill_id'), 'habilidades_tarea', ['skill_id'], unique=False)
    op.create_index(op.f('ix_habilidades_tarea_task_id'), 'habilidades_tarea', ['task_id'], unique=False)
    op.create_table('logros_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logro_id', sa.Integer(), nullable=False),
    sa.Column('desbloqueado', sa.Boolean(), nullable=False),
    sa.Column('progreso_actual', sa.Integer(), nullable=True),
    sa.Column('progreso_requerido', sa.Integer(), nullable=True),
    sa.Column('fecha_desbloqueo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notificado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['logro_id'], ['logros.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logros_usuario_id'), 'logros_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_logros_usuario_logro_id'), 'logros_usuario', ['logro_id'], unique=False)
    op.create_index(op.f('ix_logros_usuario_user_id'), 'logros_usuario', ['user_id'], unique=False)
    op.create_table('misiones_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mision_id', sa.Integer(), nullable=False),
    sa.Column('progreso_actual', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'EN_PROGRESO', 'COMPLETADA', 'EXPIRADA', name='estadomisionenum'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recompensa_reclamada', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mision_id'], ['misiones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misiones_usuario_estado'), 'misiones_usuario', ['estado'], unique=False)
    op.create_index(op.f('ix_misiones_usuario_id'), 'misiones_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_misiones_usuario_mision_id'), 'misiones_usuario', ['mision_id'], unique=False)
    op.create_index(op.f('ix_misiones_usuario_user_id'), 'misiones_usuario', ['user_id'], unique=False)
    op.create_table('transacciones_xp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_xp', sa.Integer(), nullable=False),
    sa.Column('tipo_fuente', sa.Enum('TAREA', 'LOGRO', 'MISION', 'BONUS', 'PENALIZACION', name='tipofuentexpenum'), nullable=False),
    sa.Column('fuente_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('xp_anterior', sa.Integer(), nullable=True),
    sa.Column('xp_nuevo', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_xp_created_at'), 'transacciones_xp', ['created_at'], unique=False)
    op.create_index(op.f('ix_transacciones_xp_id'), 'transacciones_xp', ['id'], unique=False)
    op.create_index(op.f('ix_transacciones_xp_tipo_fuente'), 'transacciones_xp', ['tipo_fuente'], unique=False)
    op.create_index(op.f('ix_transacciones_xp_user_id'), 'transacciones_xp', ['user_id'], unique=False)
    op.create_table('mensajes_mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='rolmensajeenum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('tiempo_respuesta_ms', sa.Integer(), nullable=True),
    sa.Column('mensaje_padre_id', sa.Integer(), nullable=True),
    sa.Column('util', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_mentor.id'], ),
    sa.ForeignKeyConstraint(['mensaje_padre_id'], ['mensajes_mentor.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentores_virtuales.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_mentor_conversacion_id'), 'mensajes_mentor', ['conversacion_id'], unique=False)
    op.create_index(op.f('ix_mensajes_mentor_created_at'), 'mensajes_mentor', ['created_at'], unique=False)
    op.create_index(op.f('ix_mensajes_mentor_id'), 'mensajes_mentor', ['id'], unique=False)
    op.create_index(op.f('ix_mensajes_mentor_mentor_id'), 'mensajes_mentor', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mensajes_mentor_rol'), 'mensajes_mentor', ['rol'], unique=False)
    op.create_index(op.f('ix_mensajes_mentor_user_id'), 'mensajes_mentor', ['user_id'], unique=False)
    op.create_table('mensajes_oraculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='rolmensajeenum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('modelo_usado', sa.String(length=100), nullable=True),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('pregunta_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_usuario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_oraculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_oraculo_created_at'), 'mensajes_oraculo', ['created_at'], unique=False)
    op.create_index(op.f('ix_mensajes_oraculo_id'), 'mensajes_oraculo', ['id'], unique=False)
    op.create_index(op.f('ix_mensajes_oraculo_rol'), 'mensajes_oraculo', ['rol'], unique=False)
    op.create_index(op.f('ix_mensajes_oraculo_sesion_id'), 'mensajes_oraculo', ['sesion_id'], unique=False)
    op.create_table('modulos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('simulacion_usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('NO_INICIADO', 'EN_PROGRESO', 'COMPLETADO', name='estadomoduloenum'), nullable=False),
    sa.Column('porcentaje_completado', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tiempo_dedicado_minutos', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['simulation_modules.id'], ),
    sa.ForeignKeyConstraint(['simulacion_usuario_id'], ['user_simulation_progress.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_usuario_estado'), 'modulos_usuario', ['estado'], unique=False)
    op.create_index(op.f('ix_modulos_usuario_id'), 'modulos_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_modulos_usuario_module_id'), 'modulos_usuario', ['module_id'], unique=False)
    op.create_index(op.f('ix_modulos_usuario_simulacion_usuario_id'), 'modulos_usuario', ['simulacion_usuario_id'], unique=False)
    op.create_index(op.f('ix_modulos_usuario_user_id'), 'modulos_usuario', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modulos_usuario_user_id'), table_name='modulos_usuario')
    op.drop_index(op.f('ix_modulos_usuario_simulacion_usuario_id'), table_name='modulos_usuario')
    op.drop_index(op.f('ix_modulos_usuario_module_id'), table_name='modulos_usuario')
    op.drop_index(op.f('ix_modulos_usuario_id'), table_name='modulos_usuario')
    op.drop_index(op.f('ix_modulos_usuario_estado'), table_name='modulos_usuario')
    op.drop_table('modulos_usuario')
    op.drop_index(op.f('ix_mensajes_oraculo_sesion_id'), table_name='mensajes_oraculo')
    op.drop_index(op.f('ix_mensajes_oraculo_rol'), table_name='mensajes_oraculo')
    op.drop_index(op.f('ix_mensajes_oraculo_id'), table_name='mensajes_oraculo')
    op.drop_index(op.f('ix_mensajes_oraculo_created_at'), table_name='mensajes_oraculo')
    op.drop_table('mensajes_oraculo')
    op.drop_index(op.f('ix_mensajes_mentor_user_id'), table_name='mensajes_mentor')
    op.drop_index(op.f('ix_mensajes_mentor_rol'), table_name='mensajes_mentor')
    op.drop_index(op.f('ix_mensajes_mentor_mentor_id'), table_name='mensajes_mentor')
    op.drop_index(op.f('ix_mensajes_mentor_id'), table_name='mensajes_mentor')
    op.drop_index(op.f('ix_mensajes_mentor_created_at'), table_name='mensajes_mentor')
    op.drop_index(op.f('ix_mensajes_mentor_conversacion_id'), table_name='mensajes_mentor')
    op.drop_table('mensajes_mentor')
    op.drop_index(op.f('ix_transacciones_xp_user_id'), table_name='transacciones_xp')
    op.drop_index(op.f('ix_transacciones_xp_tipo_fuente'), table_name='transacciones_xp')
    op.drop_index(op.f('ix_transacciones_xp_id'), table_name='transacciones_xp')
    op.drop_index(op.f('ix_transacciones_xp_created_at'), table_name='transacciones_xp')
    op.drop_table('transacciones_xp')
    op.drop_index(op.f('ix_misiones_usuario_user_id'), table_name='misiones_usuario')
    op.drop_index(op.f('ix_misiones_usuario_mision_id'), table_name='misiones_usuario')
    op.drop_index(op.f('ix_misiones_usuario_id'), table_name='misiones_usuario')
    op.drop_index(op.f('ix_misiones_usuario_estado'), table_name='misiones_usuario')
    op.drop_table('misiones_usuario')
    op.drop_index(op.f('ix_logros_usuario_user_id'), table_name='logros_usuario')
    op.drop_index(op.f('ix_logros_usuario_logro_id'), table_name='logros_usuario')
    op.drop_index(op.f('ix_logros_usuario_id'), table_name='logros_usuario')
    op.drop_table('logros_usuario')
    op.drop_index(op.f('ix_habilidades_tarea_task_id'), table_name='habilidades_tarea')
    op.drop_index(op.f('ix_habilidades_tarea_skill_id'), table_name='habilidades_tarea')
    op.drop_index(op.f('ix_habilidades_tarea_id'), table_name='habilidades_tarea')
    op.drop_table('habilidades_tarea')
    op.drop_index(op.f('ix_conversaciones_mentor_user_id'), table_name='conversaciones_mentor')
    op.drop_index(op.f('ix_conversaciones_mentor_simulation_id'), table_name='conversaciones_mentor')
    op.drop_index(op.f('ix_conversaciones_mentor_mentor_id'), table_name='conversaciones_mentor')
    op.drop_index(op.f('ix_conversaciones_mentor_id'), table_name='conversaciones_mentor')
    op.drop_index(op.f('ix_conversaciones_mentor_estado'), table_name='conversaciones_mentor')
    op.drop_table('conversaciones_mentor')
    op.drop_index(op.f('ix_mentores_virtuales_id'), table_name='mentores_virtuales')
    op.drop_index(op.f('ix_mentores_virtuales_empresa_id'), table_name='mentores_virtuales')
    op.drop_table('mentores_virtuales')
    op.drop_index(op.f('ix_misiones_id'), table_name='misiones')
    op.drop_table('misiones')
    op.drop_index(op.f('ix_logros_tipo_logro'), table_name='logros')
    op.drop_index(op.f('ix_logros_id'), table_name='logros')
    op.drop_table('logros')
    # ### end Alembic commands ###
