"""fase10_ecosistema_universitario_b2b
Revision ID: 82d6f87832a0
Revises: aa27223640d5
Create Date: 2026-03-06 03:29:50.611193
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '82d6f87832a0'
down_revision = 'aa27223640d5'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programas_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universidad_id', sa.Integer(), nullable=False),
    sa.Column('nombre_programa', sa.String(length=200), nullable=False),
    sa.Column('tipo_programa', sa.String(length=50), nullable=False, comment='pregrado, posgrado'),
    sa.Column('total_creditos', sa.Integer(), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['universidad_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programas_academicos_id'), 'programas_academicos', ['id'], unique=False)
    op.create_index(op.f('ix_programas_academicos_universidad_id'), 'programas_academicos', ['universidad_id'], unique=False)
    op.create_table('analitica_simulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('periodo_tipo', sa.String(length=50), nullable=False),
    sa.Column('total_inscritos', sa.Integer(), nullable=False),
    sa.Column('tasa_completado', sa.Float(), nullable=False),
    sa.Column('nps_score', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analitica_simulacion_empresa_id'), 'analitica_simulacion', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_analitica_simulacion_id'), 'analitica_simulacion', ['id'], unique=False)
    op.create_index(op.f('ix_analitica_simulacion_simulacion_id'), 'analitica_simulacion', ['simulacion_id'], unique=False)
    op.create_table('cohortes_simulacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_cohorte', sa.String(length=200), nullable=False),
    sa.Column('tasa_retencion_dia_7', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohortes_simulacion_id'), 'cohortes_simulacion', ['id'], unique=False)
    op.create_index(op.f('ix_cohortes_simulacion_simulacion_id'), 'cohortes_simulacion', ['simulacion_id'], unique=False)
    op.create_table('embudo_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('paso_1_nombre', sa.String(length=100), nullable=False),
    sa.Column('paso_1_usuarios', sa.Integer(), nullable=False),
    sa.Column('tasa_conversion_total', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embudo_conversion_id'), 'embudo_conversion', ['id'], unique=False)
    op.create_index(op.f('ix_embudo_conversion_simulacion_id'), 'embudo_conversion', ['simulacion_id'], unique=False)
    op.create_table('reporte_universidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universidad_id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=False, comment='ej: 2025-I, 2025-II'),
    sa.Column('total_estudiantes', sa.Integer(), nullable=False),
    sa.Column('tasa_aprobacion', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas_academicos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universidad_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_universidad_id'), 'reporte_universidad', ['id'], unique=False)
    op.create_index(op.f('ix_reporte_universidad_programa_id'), 'reporte_universidad', ['programa_id'], unique=False)
    op.create_index(op.f('ix_reporte_universidad_universidad_id'), 'reporte_universidad', ['universidad_id'], unique=False)
    op.create_table('simulaciones_programas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('es_obligatoria', sa.Boolean(), nullable=False),
    sa.Column('semestre_sugerido', sa.Integer(), nullable=True, comment='1 al 10'),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas_academicos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulaciones_programas_id'), 'simulaciones_programas', ['id'], unique=False)
    op.create_index(op.f('ix_simulaciones_programas_programa_id'), 'simulaciones_programas', ['programa_id'], unique=False)
    op.create_index(op.f('ix_simulaciones_programas_simulacion_id'), 'simulaciones_programas', ['simulacion_id'], unique=False)
    op.create_table('estudiantes_universitarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('universidad_id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.Column('estado_estudiante', sa.String(length=50), nullable=False, comment='activo, egresado, retirado'),
    sa.Column('email_institucional', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas_academicos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['universidad_id'], ['universities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_universitarios_email_institucional'), 'estudiantes_universitarios', ['email_institucional'], unique=False)
    op.create_index(op.f('ix_estudiantes_universitarios_id'), 'estudiantes_universitarios', ['id'], unique=False)
    op.create_index(op.f('ix_estudiantes_universitarios_programa_id'), 'estudiantes_universitarios', ['programa_id'], unique=False)
    op.create_index(op.f('ix_estudiantes_universitarios_universidad_id'), 'estudiantes_universitarios', ['universidad_id'], unique=False)
    op.create_index(op.f('ix_estudiantes_universitarios_usuario_id'), 'estudiantes_universitarios', ['usuario_id'], unique=False)
    op.create_table('eventos_candidato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidato_empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.String(length=100), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('metadata_evento', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidato_empresa_id'], ['candidatos_empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_candidato_candidato_empresa_id'), 'eventos_candidato', ['candidato_empresa_id'], unique=False)
    op.create_index(op.f('ix_eventos_candidato_creado_en'), 'eventos_candidato', ['creado_en'], unique=False)
    op.create_index(op.f('ix_eventos_candidato_id'), 'eventos_candidato', ['id'], unique=False)
    op.alter_column('candidatos_empresa', 'origen',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='simulacion_completada, top_performer, etc.',
               existing_nullable=False)
    op.alter_column('candidatos_empresa', 'puntuacion_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='0-100',
               existing_nullable=True)
    op.alter_column('eventos_usuario', 'evento',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='page_view, button_click, video_play',
               existing_nullable=False)
    op.alter_column('eventos_usuario', 'categoria',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='navegacion, progreso, etc.',
               existing_nullable=False)
    op.alter_column('eventos_usuario', 'metadata_evento',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON con data flexible del evento',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eventos_usuario', 'metadata_evento',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON con data flexible del evento',
               existing_nullable=True)
    op.alter_column('eventos_usuario', 'categoria',
               existing_type=sa.VARCHAR(length=50),
               comment='navegacion, progreso, etc.',
               existing_nullable=False)
    op.alter_column('eventos_usuario', 'evento',
               existing_type=sa.VARCHAR(length=100),
               comment='page_view, button_click, video_play',
               existing_nullable=False)
    op.alter_column('candidatos_empresa', 'puntuacion_total',
               existing_type=sa.INTEGER(),
               comment='0-100',
               existing_nullable=True)
    op.alter_column('candidatos_empresa', 'origen',
               existing_type=sa.VARCHAR(length=50),
               comment='simulacion_completada, top_performer, etc.',
               existing_nullable=False)
    op.drop_index(op.f('ix_eventos_candidato_id'), table_name='eventos_candidato')
    op.drop_index(op.f('ix_eventos_candidato_creado_en'), table_name='eventos_candidato')
    op.drop_index(op.f('ix_eventos_candidato_candidato_empresa_id'), table_name='eventos_candidato')
    op.drop_table('eventos_candidato')
    op.drop_index(op.f('ix_estudiantes_universitarios_usuario_id'), table_name='estudiantes_universitarios')
    op.drop_index(op.f('ix_estudiantes_universitarios_universidad_id'), table_name='estudiantes_universitarios')
    op.drop_index(op.f('ix_estudiantes_universitarios_programa_id'), table_name='estudiantes_universitarios')
    op.drop_index(op.f('ix_estudiantes_universitarios_id'), table_name='estudiantes_universitarios')
    op.drop_index(op.f('ix_estudiantes_universitarios_email_institucional'), table_name='estudiantes_universitarios')
    op.drop_table('estudiantes_universitarios')
    op.drop_index(op.f('ix_simulaciones_programas_simulacion_id'), table_name='simulaciones_programas')
    op.drop_index(op.f('ix_simulaciones_programas_programa_id'), table_name='simulaciones_programas')
    op.drop_index(op.f('ix_simulaciones_programas_id'), table_name='simulaciones_programas')
    op.drop_table('simulaciones_programas')
    op.drop_index(op.f('ix_reporte_universidad_universidad_id'), table_name='reporte_universidad')
    op.drop_index(op.f('ix_reporte_universidad_programa_id'), table_name='reporte_universidad')
    op.drop_index(op.f('ix_reporte_universidad_id'), table_name='reporte_universidad')
    op.drop_table('reporte_universidad')
    op.drop_index(op.f('ix_embudo_conversion_simulacion_id'), table_name='embudo_conversion')
    op.drop_index(op.f('ix_embudo_conversion_id'), table_name='embudo_conversion')
    op.drop_table('embudo_conversion')
    op.drop_index(op.f('ix_cohortes_simulacion_simulacion_id'), table_name='cohortes_simulacion')
    op.drop_index(op.f('ix_cohortes_simulacion_id'), table_name='cohortes_simulacion')
    op.drop_table('cohortes_simulacion')
    op.drop_index(op.f('ix_analitica_simulacion_simulacion_id'), table_name='analitica_simulacion')
    op.drop_index(op.f('ix_analitica_simulacion_id'), table_name='analitica_simulacion')
    op.drop_index(op.f('ix_analitica_simulacion_empresa_id'), table_name='analitica_simulacion')
    op.drop_table('analitica_simulacion')
    op.drop_index(op.f('ix_programas_academicos_universidad_id'), table_name='programas_academicos')
    op.drop_index(op.f('ix_programas_academicos_id'), table_name='programas_academicos')
    op.drop_table('programas_academicos')
    # ### end Alembic commands ###
