"""refactor_merge_user_extended
Revision ID: a88ccd6834a7
Revises: 383c5f20fdcd
Create Date: 2026-02-08 18:49:56.122245
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a88ccd6834a7'
down_revision = '383c5f20fdcd'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('xp_validated', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level_current', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('streak_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('preferred_lang', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'xp_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'disabled')
    op.drop_column('users', 'current_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'xp_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_lang')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'streak_days')
    op.drop_column('users', 'level_current')
    op.drop_column('users', 'xp_validated')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
