"""refactor_skills_dinamicos
Revision ID: aa27223640d5
Revises: 7c478f85c047
Create Date: 2026-03-06 03:17:33.706611
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aa27223640d5'
down_revision = '7c478f85c047'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arquetipos_psicologicos', sa.Column('min_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_column('arquetipos_psicologicos', 'min_social')
    op.drop_column('arquetipos_psicologicos', 'min_linguistic')
    op.drop_column('arquetipos_psicologicos', 'min_hands_on')
    op.drop_column('arquetipos_psicologicos', 'min_analytical')
    op.drop_column('arquetipos_psicologicos', 'min_creative')
    op.add_column('opciones_respuesta', sa.Column('skill_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_column('opciones_respuesta', 'peso_linguistic')
    op.drop_column('opciones_respuesta', 'peso_social')
    op.drop_column('opciones_respuesta', 'peso_analytical')
    op.drop_column('opciones_respuesta', 'peso_hands_on')
    op.drop_column('opciones_respuesta', 'peso_creative')
    op.add_column('sesiones_oraculo', sa.Column('inferred_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_column('sesiones_oraculo', 'score_creative')
    op.drop_column('sesiones_oraculo', 'score_social')
    op.drop_column('sesiones_oraculo', 'score_linguistic')
    op.drop_column('sesiones_oraculo', 'score_analytical')
    op.drop_column('sesiones_oraculo', 'score_hands_on')
    op.add_column('users', sa.Column('inferred_skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.drop_column('users', 'analytical_score')
    op.drop_column('users', 'creative_score')
    op.drop_column('users', 'hands_on_score')
    op.drop_column('users', 'linguistic_score')
    op.drop_column('users', 'social_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linguistic_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hands_on_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('creative_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('analytical_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('users', 'inferred_skills')
    op.add_column('sesiones_oraculo', sa.Column('score_hands_on', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiones_oraculo', sa.Column('score_analytical', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiones_oraculo', sa.Column('score_linguistic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiones_oraculo', sa.Column('score_social', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sesiones_oraculo', sa.Column('score_creative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sesiones_oraculo', 'inferred_skills')
    op.add_column('opciones_respuesta', sa.Column('peso_creative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opciones_respuesta', sa.Column('peso_hands_on', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opciones_respuesta', sa.Column('peso_analytical', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opciones_respuesta', sa.Column('peso_social', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('opciones_respuesta', sa.Column('peso_linguistic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('opciones_respuesta', 'skill_mapping')
    op.add_column('arquetipos_psicologicos', sa.Column('min_creative', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arquetipos_psicologicos', sa.Column('min_analytical', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arquetipos_psicologicos', sa.Column('min_hands_on', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arquetipos_psicologicos', sa.Column('min_linguistic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arquetipos_psicologicos', sa.Column('min_social', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('arquetipos_psicologicos', 'min_skills')
    # ### end Alembic commands ###
