"""add_catalog_tables
Revision ID: b13f8666e547
Revises: 418c1b16ee37
Create Date: 2026-01-30 23:01:08.495615
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b13f8666e547'
down_revision = '418c1b16ee37'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['content_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_categories_id'), 'content_categories', ['id'], unique=False)
    op.create_index(op.f('ix_content_categories_name'), 'content_categories', ['name'], unique=True)
    op.create_index(op.f('ix_content_categories_parent_category_id'), 'content_categories', ['parent_category_id'], unique=False)
    op.create_index(op.f('ix_content_categories_slug'), 'content_categories', ['slug'], unique=True)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('tipo_empresa', sa.String(length=50), nullable=False),
    sa.Column('industria', sa.String(length=100), nullable=False),
    sa.Column('industria_secundaria', sa.String(length=100), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=500), nullable=True),
    sa.Column('descripcion_completa', sa.Text(), nullable=True),
    sa.Column('mision', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('url_logo', sa.String(length=500), nullable=True),
    sa.Column('url_banner', sa.String(length=500), nullable=True),
    sa.Column('url_sitio_web', sa.String(length=500), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('email_contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('es_partner_activo', sa.Boolean(), nullable=False),
    sa.Column('tipo_partnership', sa.String(length=50), nullable=True),
    sa.Column('max_simulaciones_activas', sa.Integer(), nullable=True),
    sa.Column('max_usuarios_admin', sa.Integer(), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('total_simulaciones', sa.Integer(), nullable=True),
    sa.Column('total_usuarios_inscritos', sa.Integer(), nullable=True),
    sa.Column('calificacion_promedio', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nombre_empresa'), 'empresas', ['nombre_empresa'], unique=True)
    op.create_index(op.f('ix_empresas_slug'), 'empresas', ['slug'], unique=True)
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True, comment='Hex color'),
    sa.Column('parent_industry_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True, comment='1: Parent, 2: Child, 3: Grandchild'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_industry_id'], ['industries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.create_index(op.f('ix_industries_parent_industry_id'), 'industries', ['parent_industry_id'], unique=False)
    op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
    op.create_table('skills_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='technical, soft, language, tool'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_skill_id', sa.Integer(), nullable=True),
    sa.Column('taxonomy_level', sa.Integer(), nullable=True, comment='Programming → Python → Django'),
    sa.Column('market_demand', sa.String(length=20), nullable=True, comment='high, medium, low'),
    sa.Column('trend', sa.String(length=20), nullable=True, comment='growing, stable, declining'),
    sa.Column('avg_salary_impact', sa.Numeric(precision=5, scale=2), nullable=True, comment='Salary multiplier estimate'),
    sa.Column('linkedin_skill_id', sa.String(length=100), nullable=True),
    sa.Column('coursera_skill_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_catalog_category'), 'skills_catalog', ['category'], unique=False)
    op.create_index(op.f('ix_skills_catalog_id'), 'skills_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_skills_catalog_name'), 'skills_catalog', ['name'], unique=True)
    op.create_index(op.f('ix_skills_catalog_parent_skill_id'), 'skills_catalog', ['parent_skill_id'], unique=False)
    op.create_index(op.f('ix_skills_catalog_slug'), 'skills_catalog', ['slug'], unique=True)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=True),
    sa.Column('university_type', sa.Enum('public', 'private', 'cofinanced', name='universitytype'), nullable=False),
    sa.Column('accreditation', sa.Enum('A', 'B', 'C', 'pending', name='accreditationtype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=300), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_code'), 'universities', ['code'], unique=True)
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_semesters', sa.Integer(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    op.add_column('cities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_cities_province_id'), 'cities', ['province_id'], unique=False)
    op.add_column('provinces', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('provinces', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment='INEC Code',
               existing_nullable=False)
    op.drop_constraint(op.f('provinces_code_key'), 'provinces', type_='unique')
    op.drop_constraint(op.f('provinces_name_key'), 'provinces', type_='unique')
    op.create_index(op.f('ix_provinces_code'), 'provinces', ['code'], unique=True)
    op.create_index(op.f('ix_provinces_name'), 'provinces', ['name'], unique=True)
    op.create_index(op.f('ix_provinces_region_id'), 'provinces', ['region_id'], unique=False)
    op.add_column('regions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('regions', 'map_color',
               existing_type=sa.VARCHAR(length=7),
               comment='Hex color for maps',
               existing_nullable=True)
    op.drop_constraint(op.f('regions_code_key'), 'regions', type_='unique')
    op.drop_constraint(op.f('regions_name_key'), 'regions', type_='unique')
    op.create_index(op.f('ix_regions_code'), 'regions', ['code'], unique=True)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_code'), table_name='regions')
    op.create_unique_constraint(op.f('regions_name_key'), 'regions', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('regions_code_key'), 'regions', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('regions', 'map_color',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Hex color for maps',
               existing_nullable=True)
    op.drop_column('regions', 'created_at')
    op.drop_index(op.f('ix_provinces_region_id'), table_name='provinces')
    op.drop_index(op.f('ix_provinces_name'), table_name='provinces')
    op.drop_index(op.f('ix_provinces_code'), table_name='provinces')
    op.create_unique_constraint(op.f('provinces_name_key'), 'provinces', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('provinces_code_key'), 'provinces', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('provinces', 'code',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='INEC Code',
               existing_nullable=False)
    op.drop_column('provinces', 'created_at')
    op.drop_index(op.f('ix_cities_province_id'), table_name='cities')
    op.drop_column('cities', 'created_at')
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_table('careers')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_code'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_skills_catalog_slug'), table_name='skills_catalog')
    op.drop_index(op.f('ix_skills_catalog_parent_skill_id'), table_name='skills_catalog')
    op.drop_index(op.f('ix_skills_catalog_name'), table_name='skills_catalog')
    op.drop_index(op.f('ix_skills_catalog_id'), table_name='skills_catalog')
    op.drop_index(op.f('ix_skills_catalog_category'), table_name='skills_catalog')
    op.drop_table('skills_catalog')
    op.drop_index(op.f('ix_industries_slug'), table_name='industries')
    op.drop_index(op.f('ix_industries_parent_industry_id'), table_name='industries')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_empresas_slug'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre_empresa'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_content_categories_slug'), table_name='content_categories')
    op.drop_index(op.f('ix_content_categories_parent_category_id'), table_name='content_categories')
    op.drop_index(op.f('ix_content_categories_name'), table_name='content_categories')
    op.drop_index(op.f('ix_content_categories_id'), table_name='content_categories')
    op.drop_table('content_categories')
    # ### end Alembic commands ###
