"""add_learning_paths
Revision ID: b47178168b0e
Revises: 72c9aac5e073
Create Date: 2026-08-09 02:17:09.523406
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b47178168b0e'
down_revision = '72c9aac5e073'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
