"""add_company_users
Revision ID: c05833cd04f9
Revises: b13f8666e547
Create Date: 2026-01-30 23:18:29.834510
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c05833cd04f9'
down_revision = 'b13f8666e547'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True, comment='Recruiter, Content Manager, HR Director'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False, comment='owner, admin, editor, viewer'),
    sa.Column('can_create_simulations', sa.Boolean(), nullable=True),
    sa.Column('can_edit_simulations', sa.Boolean(), nullable=True),
    sa.Column('can_publish_simulations', sa.Boolean(), nullable=True),
    sa.Column('can_archive_simulations', sa.Boolean(), nullable=True),
    sa.Column('can_view_candidates', sa.Boolean(), nullable=True),
    sa.Column('can_contact_candidates', sa.Boolean(), nullable=True),
    sa.Column('can_export_data', sa.Boolean(), nullable=True),
    sa.Column('can_manage_users', sa.Boolean(), nullable=True),
    sa.Column('can_view_billing', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_access', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_accesses', sa.Integer(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invitation_token', sa.String(length=100), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['company_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_users_company_id'), 'company_users', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_users_email'), 'company_users', ['email'], unique=True)
    op.create_index(op.f('ix_company_users_id'), 'company_users', ['id'], unique=False)
    op.create_index(op.f('ix_company_users_invitation_token'), 'company_users', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_company_users_role'), 'company_users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_users_role'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_invitation_token'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_id'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_email'), table_name='company_users')
    op.drop_index(op.f('ix_company_users_company_id'), table_name='company_users')
    op.drop_table('company_users')
    # ### end Alembic commands ###
