"""fase11_enterprise_social_soporte
Revision ID: c5ef71b33e6b
Revises: 82d6f87832a0
Create Date: 2026-03-06 04:50:59.411472
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c5ef71b33e6b'
down_revision = '82d6f87832a0'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('es_activo', sa.Boolean(), nullable=False),
    sa.Column('caracteristicas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_suscripcion_id'), 'planes_suscripcion', ['id'], unique=False)
    op.create_index(op.f('ix_planes_suscripcion_nombre'), 'planes_suscripcion', ['nombre'], unique=True)
    op.create_table('admins_dao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_dao_id'), 'admins_dao', ['id'], unique=False)
    op.create_index(op.f('ix_admins_dao_user_id'), 'admins_dao', ['user_id'], unique=True)
    op.create_table('feedback_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_general_creado_en'), 'feedback_general', ['creado_en'], unique=False)
    op.create_index(op.f('ix_feedback_general_id'), 'feedback_general', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_general_user_id'), 'feedback_general', ['user_id'], unique=False)
    op.create_table('intentos_fraudulentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('tipo_intento', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intentos_fraudulentos_creado_en'), 'intentos_fraudulentos', ['creado_en'], unique=False)
    op.create_index(op.f('ix_intentos_fraudulentos_id'), 'intentos_fraudulentos', ['id'], unique=False)
    op.create_index(op.f('ix_intentos_fraudulentos_ip_address'), 'intentos_fraudulentos', ['ip_address'], unique=False)
    op.create_index(op.f('ix_intentos_fraudulentos_user_id'), 'intentos_fraudulentos', ['user_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('link_accion', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_creado_en'), 'notificaciones', ['creado_en'], unique=False)
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.create_index(op.f('ix_notificaciones_user_id'), 'notificaciones', ['user_id'], unique=False)
    op.create_table('preferencias_notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_marketing', sa.Boolean(), nullable=False),
    sa.Column('email_alertas', sa.Boolean(), nullable=False),
    sa.Column('push_social', sa.Boolean(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preferencias_notificaciones_id'), 'preferencias_notificaciones', ['id'], unique=False)
    op.create_index(op.f('ix_preferencias_notificaciones_user_id'), 'preferencias_notificaciones', ['user_id'], unique=True)
    op.create_table('publicaciones_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicaciones_feed_creado_en'), 'publicaciones_feed', ['creado_en'], unique=False)
    op.create_index(op.f('ix_publicaciones_feed_id'), 'publicaciones_feed', ['id'], unique=False)
    op.create_index(op.f('ix_publicaciones_feed_user_id'), 'publicaciones_feed', ['user_id'], unique=False)
    op.create_table('suscripciones_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metodo_pago', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_suscripcion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_usuario_estado'), 'suscripciones_usuario', ['estado'], unique=False)
    op.create_index(op.f('ix_suscripciones_usuario_id'), 'suscripciones_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_suscripciones_usuario_plan_id'), 'suscripciones_usuario', ['plan_id'], unique=False)
    op.create_index(op.f('ix_suscripciones_usuario_user_id'), 'suscripciones_usuario', ['user_id'], unique=False)
    op.create_table('tickets_soporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('prioridad', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_soporte_creado_en'), 'tickets_soporte', ['creado_en'], unique=False)
    op.create_index(op.f('ix_tickets_soporte_estado'), 'tickets_soporte', ['estado'], unique=False)
    op.create_index(op.f('ix_tickets_soporte_id'), 'tickets_soporte', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_soporte_user_id'), 'tickets_soporte', ['user_id'], unique=False)
    op.create_table('transacciones_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('id_transaccion_pasarela', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_suscripcion.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_pago_creado_en'), 'transacciones_pago', ['creado_en'], unique=False)
    op.create_index(op.f('ix_transacciones_pago_estado'), 'transacciones_pago', ['estado'], unique=False)
    op.create_index(op.f('ix_transacciones_pago_id'), 'transacciones_pago', ['id'], unique=False)
    op.create_index(op.f('ix_transacciones_pago_id_transaccion_pasarela'), 'transacciones_pago', ['id_transaccion_pasarela'], unique=True)
    op.create_index(op.f('ix_transacciones_pago_plan_id'), 'transacciones_pago', ['plan_id'], unique=False)
    op.create_index(op.f('ix_transacciones_pago_user_id'), 'transacciones_pago', ['user_id'], unique=False)
    op.create_table('mensajes_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('es_staff', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_soporte.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_ticket_creado_en'), 'mensajes_ticket', ['creado_en'], unique=False)
    op.create_index(op.f('ix_mensajes_ticket_id'), 'mensajes_ticket', ['id'], unique=False)
    op.create_index(op.f('ix_mensajes_ticket_ticket_id'), 'mensajes_ticket', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_mensajes_ticket_user_id'), 'mensajes_ticket', ['user_id'], unique=False)
    op.create_table('publicaciones_comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['publicaciones_feed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicaciones_comentarios_creado_en'), 'publicaciones_comentarios', ['creado_en'], unique=False)
    op.create_index(op.f('ix_publicaciones_comentarios_id'), 'publicaciones_comentarios', ['id'], unique=False)
    op.create_index(op.f('ix_publicaciones_comentarios_post_id'), 'publicaciones_comentarios', ['post_id'], unique=False)
    op.create_index(op.f('ix_publicaciones_comentarios_user_id'), 'publicaciones_comentarios', ['user_id'], unique=False)
    op.create_table('publicaciones_guardadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['publicaciones_feed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_guardado_post_usuario')
    )
    op.create_index(op.f('ix_publicaciones_guardadas_id'), 'publicaciones_guardadas', ['id'], unique=False)
    op.create_index(op.f('ix_publicaciones_guardadas_post_id'), 'publicaciones_guardadas', ['post_id'], unique=False)
    op.create_index(op.f('ix_publicaciones_guardadas_user_id'), 'publicaciones_guardadas', ['user_id'], unique=False)
    op.create_table('publicaciones_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['publicaciones_feed.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_like_post_usuario')
    )
    op.create_index(op.f('ix_publicaciones_likes_id'), 'publicaciones_likes', ['id'], unique=False)
    op.create_index(op.f('ix_publicaciones_likes_post_id'), 'publicaciones_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_publicaciones_likes_user_id'), 'publicaciones_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publicaciones_likes_user_id'), table_name='publicaciones_likes')
    op.drop_index(op.f('ix_publicaciones_likes_post_id'), table_name='publicaciones_likes')
    op.drop_index(op.f('ix_publicaciones_likes_id'), table_name='publicaciones_likes')
    op.drop_table('publicaciones_likes')
    op.drop_index(op.f('ix_publicaciones_guardadas_user_id'), table_name='publicaciones_guardadas')
    op.drop_index(op.f('ix_publicaciones_guardadas_post_id'), table_name='publicaciones_guardadas')
    op.drop_index(op.f('ix_publicaciones_guardadas_id'), table_name='publicaciones_guardadas')
    op.drop_table('publicaciones_guardadas')
    op.drop_index(op.f('ix_publicaciones_comentarios_user_id'), table_name='publicaciones_comentarios')
    op.drop_index(op.f('ix_publicaciones_comentarios_post_id'), table_name='publicaciones_comentarios')
    op.drop_index(op.f('ix_publicaciones_comentarios_id'), table_name='publicaciones_comentarios')
    op.drop_index(op.f('ix_publicaciones_comentarios_creado_en'), table_name='publicaciones_comentarios')
    op.drop_table('publicaciones_comentarios')
    op.drop_index(op.f('ix_mensajes_ticket_user_id'), table_name='mensajes_ticket')
    op.drop_index(op.f('ix_mensajes_ticket_ticket_id'), table_name='mensajes_ticket')
    op.drop_index(op.f('ix_mensajes_ticket_id'), table_name='mensajes_ticket')
    op.drop_index(op.f('ix_mensajes_ticket_creado_en'), table_name='mensajes_ticket')
    op.drop_table('mensajes_ticket')
    op.drop_index(op.f('ix_transacciones_pago_user_id'), table_name='transacciones_pago')
    op.drop_index(op.f('ix_transacciones_pago_plan_id'), table_name='transacciones_pago')
    op.drop_index(op.f('ix_transacciones_pago_id_transaccion_pasarela'), table_name='transacciones_pago')
    op.drop_index(op.f('ix_transacciones_pago_id'), table_name='transacciones_pago')
    op.drop_index(op.f('ix_transacciones_pago_estado'), table_name='transacciones_pago')
    op.drop_index(op.f('ix_transacciones_pago_creado_en'), table_name='transacciones_pago')
    op.drop_table('transacciones_pago')
    op.drop_index(op.f('ix_tickets_soporte_user_id'), table_name='tickets_soporte')
    op.drop_index(op.f('ix_tickets_soporte_id'), table_name='tickets_soporte')
    op.drop_index(op.f('ix_tickets_soporte_estado'), table_name='tickets_soporte')
    op.drop_index(op.f('ix_tickets_soporte_creado_en'), table_name='tickets_soporte')
    op.drop_table('tickets_soporte')
    op.drop_index(op.f('ix_suscripciones_usuario_user_id'), table_name='suscripciones_usuario')
    op.drop_index(op.f('ix_suscripciones_usuario_plan_id'), table_name='suscripciones_usuario')
    op.drop_index(op.f('ix_suscripciones_usuario_id'), table_name='suscripciones_usuario')
    op.drop_index(op.f('ix_suscripciones_usuario_estado'), table_name='suscripciones_usuario')
    op.drop_table('suscripciones_usuario')
    op.drop_index(op.f('ix_publicaciones_feed_user_id'), table_name='publicaciones_feed')
    op.drop_index(op.f('ix_publicaciones_feed_id'), table_name='publicaciones_feed')
    op.drop_index(op.f('ix_publicaciones_feed_creado_en'), table_name='publicaciones_feed')
    op.drop_table('publicaciones_feed')
    op.drop_index(op.f('ix_preferencias_notificaciones_user_id'), table_name='preferencias_notificaciones')
    op.drop_index(op.f('ix_preferencias_notificaciones_id'), table_name='preferencias_notificaciones')
    op.drop_table('preferencias_notificaciones')
    op.drop_index(op.f('ix_notificaciones_user_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_creado_en'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_intentos_fraudulentos_user_id'), table_name='intentos_fraudulentos')
    op.drop_index(op.f('ix_intentos_fraudulentos_ip_address'), table_name='intentos_fraudulentos')
    op.drop_index(op.f('ix_intentos_fraudulentos_id'), table_name='intentos_fraudulentos')
    op.drop_index(op.f('ix_intentos_fraudulentos_creado_en'), table_name='intentos_fraudulentos')
    op.drop_table('intentos_fraudulentos')
    op.drop_index(op.f('ix_feedback_general_user_id'), table_name='feedback_general')
    op.drop_index(op.f('ix_feedback_general_id'), table_name='feedback_general')
    op.drop_index(op.f('ix_feedback_general_creado_en'), table_name='feedback_general')
    op.drop_table('feedback_general')
    op.drop_index(op.f('ix_admins_dao_user_id'), table_name='admins_dao')
    op.drop_index(op.f('ix_admins_dao_id'), table_name='admins_dao')
    op.drop_table('admins_dao')
    op.drop_index(op.f('ix_planes_suscripcion_nombre'), table_name='planes_suscripcion')
    op.drop_index(op.f('ix_planes_suscripcion_id'), table_name='planes_suscripcion')
    op.drop_table('planes_suscripcion')
    # ### end Alembic commands ###
