"""implementacion_arquitectura_ia
Revision ID: cffe39e02ec2
Revises: 6df5fed3d32b
Create Date: 2026-03-02 21:00:43.053076
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cffe39e02ec2'
down_revision = '6df5fed3d32b'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendaciones_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('simulacion_id', sa.Integer(), nullable=False),
    sa.Column('engagement_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('razon_principal', sa.String(length=200), nullable=True),
    sa.Column('fue_clickeado', sa.Boolean(), nullable=True),
    sa.Column('fue_iniciado', sa.Boolean(), nullable=True),
    sa.Column('generado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['simulacion_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_ia_id'), 'recomendaciones_ia', ['id'], unique=False)
    op.create_index(op.f('ix_recomendaciones_ia_simulacion_id'), 'recomendaciones_ia', ['simulacion_id'], unique=False)
    op.create_index(op.f('ix_recomendaciones_ia_usuario_id'), 'recomendaciones_ia', ['usuario_id'], unique=False)
    op.add_column('simulations', sa.Column('industria_principal_id', sa.Integer(), nullable=True, comment='Desnormalizado para IA'))
    op.create_index(op.f('ix_simulations_industria_principal_id'), 'simulations', ['industria_principal_id'], unique=False)
    op.add_column('users', sa.Column('nivel_educativo', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('campo_estudio', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('nombre_institucion', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('analytical_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('creative_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('social_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('linguistic_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hands_on_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('origen_datos', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'origen_datos')
    op.drop_column('users', 'hands_on_score')
    op.drop_column('users', 'linguistic_score')
    op.drop_column('users', 'social_score')
    op.drop_column('users', 'creative_score')
    op.drop_column('users', 'analytical_score')
    op.drop_column('users', 'nombre_institucion')
    op.drop_column('users', 'campo_estudio')
    op.drop_column('users', 'nivel_educativo')
    op.drop_index(op.f('ix_simulations_industria_principal_id'), table_name='simulations')
    op.drop_column('simulations', 'industria_principal_id')
    op.drop_index(op.f('ix_recomendaciones_ia_usuario_id'), table_name='recomendaciones_ia')
    op.drop_index(op.f('ix_recomendaciones_ia_simulacion_id'), table_name='recomendaciones_ia')
    op.drop_index(op.f('ix_recomendaciones_ia_id'), table_name='recomendaciones_ia')
    op.drop_table('recomendaciones_ia')
    # ### end Alembic commands ###
