"""fase7_motor_oraculo
Revision ID: d84a40a32a43
Revises: 421658025665
Create Date: 2026-03-04 20:47:21.760565
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd84a40a32a43'
down_revision = '421658025665'
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquetipos_psicologicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('min_analytical', sa.Integer(), nullable=True),
    sa.Column('min_creative', sa.Integer(), nullable=True),
    sa.Column('min_social', sa.Integer(), nullable=True),
    sa.Column('min_linguistic', sa.Integer(), nullable=True),
    sa.Column('min_hands_on', sa.Integer(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_arquetipos_psicologicos_id'), 'arquetipos_psicologicos', ['id'], unique=False)
    op.create_table('preguntas_oraculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('dificultad', sa.Integer(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_oraculo_id'), 'preguntas_oraculo', ['id'], unique=False)
    op.create_table('opciones_respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('peso_analytical', sa.Integer(), nullable=True),
    sa.Column('peso_creative', sa.Integer(), nullable=True),
    sa.Column('peso_social', sa.Integer(), nullable=True),
    sa.Column('peso_linguistic', sa.Integer(), nullable=True),
    sa.Column('peso_hands_on', sa.Integer(), nullable=True),
    sa.Column('explicacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_oraculo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opciones_respuesta_id'), 'opciones_respuesta', ['id'], unique=False)
    op.create_table('sesiones_oraculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('paso_actual', sa.Integer(), nullable=True),
    sa.Column('score_analytical', sa.Integer(), nullable=True),
    sa.Column('score_creative', sa.Integer(), nullable=True),
    sa.Column('score_social', sa.Integer(), nullable=True),
    sa.Column('score_linguistic', sa.Integer(), nullable=True),
    sa.Column('score_hands_on', sa.Integer(), nullable=True),
    sa.Column('arquetipo_resultante_id', sa.Integer(), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['arquetipo_resultante_id'], ['arquetipos_psicologicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_oraculo_id'), 'sesiones_oraculo', ['id'], unique=False)
    op.create_table('respuestas_usuario_oraculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_id', sa.Integer(), nullable=False),
    sa.Column('opcion_id', sa.Integer(), nullable=False),
    sa.Column('tiempo_respuesta_segundos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['opcion_id'], ['opciones_respuesta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_oraculo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_oraculo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sesion_id', 'pregunta_id', name='uq_sesion_pregunta')
    )
    op.create_index(op.f('ix_respuestas_usuario_oraculo_id'), 'respuestas_usuario_oraculo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respuestas_usuario_oraculo_id'), table_name='respuestas_usuario_oraculo')
    op.drop_table('respuestas_usuario_oraculo')
    op.drop_index(op.f('ix_sesiones_oraculo_id'), table_name='sesiones_oraculo')
    op.drop_table('sesiones_oraculo')
    op.drop_index(op.f('ix_opciones_respuesta_id'), table_name='opciones_respuesta')
    op.drop_table('opciones_respuesta')
    op.drop_index(op.f('ix_preguntas_oraculo_id'), table_name='preguntas_oraculo')
    op.drop_table('preguntas_oraculo')
    op.drop_index(op.f('ix_arquetipos_psicologicos_id'), table_name='arquetipos_psicologicos')
    op.drop_table('arquetipos_psicologicos')
    # ### end Alembic commands ###
