"""fase8_telemetria_y_b2b
Revision ID: db3b8b69b41e
Revises: d84a40a32a43
Create Date: 2026-03-04 21:01:29.692450
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'db3b8b69b41e'
down_revision = 'd84a40a32a43'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False, comment='simulacion_completada, top_performer, etc.'),
    sa.Column('simulacion_origen_id', sa.Integer(), nullable=True),
    sa.Column('estado_candidato', sa.String(length=50), nullable=False),
    sa.Column('puntuacion_total', sa.Integer(), nullable=True, comment='0-100'),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('etiquetas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contactado', sa.Boolean(), nullable=True),
    sa.Column('fecha_contacto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_agregado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulacion_origen_id'], ['simulations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'usuario_id', name='uq_empresa_candidato')
    )
    op.create_index(op.f('ix_candidatos_empresa_empresa_id'), 'candidatos_empresa', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_candidatos_empresa_estado_candidato'), 'candidatos_empresa', ['estado_candidato'], unique=False)
    op.create_index(op.f('ix_candidatos_empresa_id'), 'candidatos_empresa', ['id'], unique=False)
    op.create_index(op.f('ix_candidatos_empresa_usuario_id'), 'candidatos_empresa', ['usuario_id'], unique=False)
    op.create_table('eventos_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=False, comment='page_view, button_click, video_play'),
    sa.Column('categoria', sa.String(length=50), nullable=False, comment='navegacion, progreso, etc.'),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('metadata_evento', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON con data flexible del evento'),
    sa.Column('sesion_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('plataforma', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_usuario_categoria'), 'eventos_usuario', ['categoria'], unique=False)
    op.create_index(op.f('ix_eventos_usuario_creado_en'), 'eventos_usuario', ['creado_en'], unique=False)
    op.create_index(op.f('ix_eventos_usuario_evento'), 'eventos_usuario', ['evento'], unique=False)
    op.create_index(op.f('ix_eventos_usuario_id'), 'eventos_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_usuario_usuario_id'), 'eventos_usuario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eventos_usuario_usuario_id'), table_name='eventos_usuario')
    op.drop_index(op.f('ix_eventos_usuario_id'), table_name='eventos_usuario')
    op.drop_index(op.f('ix_eventos_usuario_evento'), table_name='eventos_usuario')
    op.drop_index(op.f('ix_eventos_usuario_creado_en'), table_name='eventos_usuario')
    op.drop_index(op.f('ix_eventos_usuario_categoria'), table_name='eventos_usuario')
    op.drop_table('eventos_usuario')
    op.drop_index(op.f('ix_candidatos_empresa_usuario_id'), table_name='candidatos_empresa')
    op.drop_index(op.f('ix_candidatos_empresa_id'), table_name='candidatos_empresa')
    op.drop_index(op.f('ix_candidatos_empresa_estado_candidato'), table_name='candidatos_empresa')
    op.drop_index(op.f('ix_candidatos_empresa_empresa_id'), table_name='candidatos_empresa')
    op.drop_table('candidatos_empresa')
    # ### end Alembic commands ###
